// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHH6HgYTza5CZPQ7oIHnG_3V6Ur-TBUEg',
    appId: '1:456845405290:web:5e18a7e643d9a3221fae13',
    messagingSenderId: '456845405290',
    projectId: 'points-flett-map',
    authDomain: 'points-flett-map.firebaseapp.com',
    storageBucket: 'points-flett-map.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ydOLM0B-4qgL9pBoGLToYLg1z0c1Tr4',
    appId: '1:456845405290:android:e9613f1961f75aca1fae13',
    messagingSenderId: '456845405290',
    projectId: 'points-flett-map',
    storageBucket: 'points-flett-map.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_s-EunPbAN61UZZdZ3dcxZR0n3jD_GIo',
    appId: '1:456845405290:ios:db53f04d605dcab51fae13',
    messagingSenderId: '456845405290',
    projectId: 'points-flett-map',
    storageBucket: 'points-flett-map.firebasestorage.app',
    iosBundleId: 'com.example.pointsFlettMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_s-EunPbAN61UZZdZ3dcxZR0n3jD_GIo',
    appId: '1:456845405290:ios:db53f04d605dcab51fae13',
    messagingSenderId: '456845405290',
    projectId: 'points-flett-map',
    storageBucket: 'points-flett-map.firebasestorage.app',
    iosBundleId: 'com.example.pointsFlettMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHH6HgYTza5CZPQ7oIHnG_3V6Ur-TBUEg',
    appId: '1:456845405290:web:32448bd2eeb2d51b1fae13',
    messagingSenderId: '456845405290',
    projectId: 'points-flett-map',
    authDomain: 'points-flett-map.firebaseapp.com',
    storageBucket: 'points-flett-map.firebasestorage.app',
  );
}
